---
- name: Create work directory
  file:
    path: /Users/{{ work_user }}/{{ work_dir }}
    state: directory
    mode: 0777

- name: Clone TenantCloud promo project
  git:
    repo: "{{ promo_git }}"
    dest: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}
    version: "{{ promo_git_branch }}"
    force: true

- name: Copy and setup TenantCloud promo environment file
  copy:
    src: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env.example
    dest: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    remote_src: true

- name: Change APP_VERSION
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^APP_VERSION='
    line: 'APP_VERSION=local'

- name: Change APP_ENV
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^APP_ENV='
    line: 'APP_ENV=local'

- name: Add APP_KEY
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^APP_KEY='
    line: 'APP_KEY={{ app_key }}'

- name: Add APP_URL
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^APP_URL='
    line: 'APP_URL=http://www.{{ work_domain }}'

- name: Add BROADCAST_DRIVER
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^BROADCAST_DRIVER='
    line: 'BROADCAST_DRIVER=file'

- name: Change CACHE_DRIVER
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^CACHE_DRIVER='
    line: 'CACHE_DRIVER=file'

- name: Change SESSION_DRIVER
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: 'SESSION_DRIVER='
    line: 'SESSION_DRIVER=file'

- name: Change QUEUE_DRIVER
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: 'QUEUE_DRIVER='
    line: 'QUEUE_DRIVER=sync'

- name: Add HOST
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^HOST='
    line: 'HOST={{ work_domain }}'

- name: Add MAIL_DRIVER
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^MAIL_DRIVER='
    line: 'MAIL_DRIVER=smtp'

- name: Add MAIL_USERNAME
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^MAIL_USERNAME='
    line: '#MAIL_USERNAME=null'

- name: Add MAIL_PASSWORD
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^MAIL_PASSWORD='
    line: '#MAIL_PASSWORD=null'

- name: Change MAIL_ENCRYPTION
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^MAIL_ENCRYPTION='
    line: '#MAIL_ENCRYPTION=null'

- name: Add S3_KEY
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^S3_KEY='
    line: 'S3_KEY={{ minio_key }}'

- name: Add S3_SECRET_KEY
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^S3_SECRET_KEY='
    line: 'S3_SECRET_KEY={{ minio_secret }}'

- name: Add S3_BUCKET
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^S3_BUCKET='
    line: 'S3_BUCKET=local'

- name: Add S3_AWS_URL
  lineinfile:
    path: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/.env
    regexp: '^S3_AWS_URL='
    line: 'S3_AWS_URL=https://home.{{ work_domain }}:9002'
