---
- name: Run deploy promo script
  command: $HOME/{{ work_dir }}/www.{{ work_domain }}/sh/update.sh
  args:
    executable: /bin/zsh
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false

- name: Restart nginx
  become: true
  command: /usr/local/bin/brew services restart nginx
  changed_when: false
