---
- name: Run deploy promo script
  command: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/sh/update.sh
  args:
    executable: /bin/zsh
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/Users/{{ work_user }}/.yarn/bin/:/Users/{{ work_user }}/.nvm/versions/node/{{ nvm_node_version }}/bin/"
  changed_when: false

- name: Restart nginx
  become: true
  command: /usr/local/bin/brew services restart nginx
  changed_when: false

- name: Copy info file
  become: true
  template: src=info.txt.j2 dest=/Users/{{ work_user }}/Desktop/{{ role_name }}.txt
