---
- name: Run deploy promo script
  command: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/sh/update.sh
  args:
    executable: /bin/zsh
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false

- name: Restart nginx
  become: true
  command: /usr/local/bin/brew services restart nginx
  changed_when: false

- name: Copy info file
  become: true
  template: src=info.txt.j2 dest=/Users/{{ work_user }}/Desktop/{{ promo_dir }}.txt
