---
- name: Run deploy promo script
  command: /Users/{{ work_user }}/{{ work_dir }}/{{ promo_dir }}/sh/update.sh
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  changed_when: false

- name: Restart nginx
  become: true
  command: /usr/local/bin/brew services restart nginx
  changed_when: false
